# Generated by Django 5.1.2 on 2024-11-04 21:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_animal', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('peso', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fecha_nacimiento', models.DateField()),
                ('salud', models.CharField(choices=[('sano', 'Sano'), ('enfermo', 'Enfermo'), ('herido', 'Herido'), ('vejez', 'Vejez')], max_length=20)),
                ('procedencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('duracion_estancia', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitats', to='app_6.animal')),
            ],
        ),
    ]
